### DISCUSSION TITLE
Enable darkmode

### DISCUSSION THREAD

**Discussion by nguyenvanduocit** [nguyenvanduocit/obsidian-open-gate#54] [snippets]
You can use custom css (solution from @andrewmcgivery):

```css
/* Invert the entire website */
html {
    -webkit-filter: invert(90%) hue-rotate(180deg)!important;
    filter: invert(90%) hue-rotate(180deg)!important;
    background: rgb(25, 25, 25)!important;
}

img,
svg {
    filter: invert(100%) hue-rotate(180deg) brightness(1.1) contrast(105%)!important;
}
```

Or custom JS:

```js
const script = document.createElement('script');
script.src = 'https://cdn.jsdelivr.net/npm/darkreader@4.9/darkreader.min.js';
script.onload = () => {  
DarkReader.enable({
    brightness: 100,
    contrast: 90,
    sepia: 10
  });
};
document.head.appendChild(script);
```
