### DISCUSSION TITLE
More minimal Deezer on the side

### DISCUSSION THREAD

**Discussion by MelodyDuplaix** [nguyenvanduocit/obsidian-open-gate#61] [snippets]
I wanted to integrate Deezer so I could listen to music but I found the site a little too cluttered. So I made this snippet to make it a little more "minimalist". If you have any tips for improving it, don't hesitate!

```css
body {
    --layout-sidebar-width: 60px !important;
    --tempo-sizes-size-xl: 25px !important;
    --grid-containers-xs: 475px !important;
    --grid-offset-xs: 26px !important;
}
.naboo {
    --layout-player-height: 180px !important;
}
.css-mopb75 {
    display: none !important;
}
.page-topbar {
    min-width: 280px !important;
}
.css-5o8yww {
    font-size: x-small !important;
}
a[href="/fr/channels/explore/explore-tab"] {
    display: none !important;
}
a[href="/fr/profile/1202735962"] {
    display: none !important;
}
div[role="group"].css-rpdt7i {
    display: none !important;
}
.css-tzddi9 {
    flex-direction: column !important;
    align-items: start !important;
    min-width: 1000px !important;
    width: 1000px !important;
    justify-content: start !important;
}
```
