### ISSUE TITLE
[BUG]: Too much long line "remove" / "hide" button

### ISSUE THREAD

**Issue by Lisandra-dev** [nguyenvanduocit/obsidian-open-gate#12]
Note : theme used is Anuppicin, maybe it's different with other theme.

![image](https://user-images.githubusercontent.com/30244939/228484368-0fb5b3bb-5d53-4c43-99da-1ac121373c8e.png)

Can be fixed using some css with, for example : 
```css
[data-gate-id] > .setting-item > .setting-item-info > .setting-item-description {
	max-width: 50em;
	overflow: hidden;
}
```
